version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: julian@gmail.com
      PGADMIN_DEFAULT_PASSWORD: julian1234
    ports:
      - "5050:80"

volumes:
  postgres_data:
